# vim: noai:ts=2:sw=2:et
---

#
# Create a 3-tier Network Infrastructure on Fujitsu K5
#
# v1.0 - 02 Jan 2017 - Nicholas Cross / Mohclips - initial release
#

- name: "Create 3-tier network K5 infrastructure"

  hosts: localhost
  connection: local
  gather_facts: no

  # batch - run 10 tasks at a time when looped- useful when creating bulk compute instances
  serial: 10


  vars:
    # use the include_vars instead to read vars/

    #
    # FLAGS: tags to turn on/off features - for faster testing ;)
    #
    # t_secgrp
    # t_network
    # t_router
    # t_jumpsvr

    K5_DEBUG: "{{ lookup('env','K5_DEBUG')|default(False) }}"

  tasks:
########################################################################################################
    - block:
      # we pull in our vars from everything in the 'vars' folder
      - include_vars:
          dir: "vars"
          depth: 1

      #
      # Authenticate to K5
      #
      - name: "Authenticate to K5"
        # use openrc environment variables
        k5_auth:
        register: k5_auth_reg

      - debug: var=k5_auth_reg.k5_auth_facts.auth_token
      tags: always

########################################################################################################
